### ISSUE TITLE
Memory usage spiked in master

### ISSUE THREAD

**Issue by michael-erasmus** [looker/lookerbot#100]
@wilg 

We're deploying Lookerbot on a Kubernetes cluster where we have memory limits in place. While running on version 0.0.11 and monitoring the RAM usage we were averaging about  ~90MiB and pretty stable, well below our memory limit of 160MiB. 

![image](https://cloud.githubusercontent.com/assets/58212/26655818/525ad43e-4611-11e7-9b05-c5bbf101e75f.png)

Since upgrading to the latest version the app's memory usage has spiked a lot, it seems to be spiking above 400MiB, making it hard to set reliable memory limits. We can get around the issue by not enforcing any limit, but it's pretty surprising that the app should use so much more memory. 

![image](https://cloud.githubusercontent.com/assets/58212/26655858/74cf8e06-4611-11e7-9044-e43801b9804a.png)

Any ideas or advice on how to deal with this?

**Comment by michael-erasmus** [comment]
Just an update, after some investigation it seems like we're seeing memory issue on the `master` branch. After we pulled 0.0.12 the memory seems to be stable. 

It seems like perhaps the refactor to Typescript might be what's causing the usage to spike. For now we can just stay on 0.0.12, but thought we might still send a heads up of this issue as you're working on the Typescript refactor.

**Comment by wilg** [comment]
Thanks @michael-erasmus – really useful info. There's the language change and also some related refactors so I'll pin this down. 

Are you using the same version of node in both cases?

**Comment by djfarrelly** [comment]
Hi @wilg,
We're using the `Dockerfile` in master for building both images so it should be 6.10.3 in both [0.0.12](https://github.com/looker/lookerbot/blob/0.0.12/Dockerfile) and [master](https://github.com/looker/lookerbot/blob/d31eb5dae4462e04c26fce560794cafa24a8533e/Dockerfile).

**Comment by wilg** [comment]
[I updated ts-node](https://github.com/looker/lookerbot/pull/129) and it appears to have reduced the memory usage by about half for our internal lookerbot. If all's well I'll release an updated version soon, or you can use the master version to try yourself.

<img width="110" alt="screen shot 2017-12-13 at 3 41 20 pm" src="https://user-images.githubusercontent.com/54353/33968285-16f69428-e01c-11e7-954f-8337b8b69ca4.png">

**Comment by wilg** [comment]
Calling this closed based on the above result.
