### ISSUE TITLE
Use AWS roles instead of keys

### ISSUE THREAD

**Issue by morganatlooker** [looker/lookerbot#112]
For a client who wants to reduce the number of AWS api keys floating out in the ether!

**Comment by georgeismike** [comment]
EC2 will automatically use role assigned to the instance.  So the keys are really only needed/used for local development. @morganatlooker

**Comment by reedloden** [comment]
Yes, we already use IAM roles for our Lookerbot without any need for static IAM keys.

**Comment by wilg** [comment]
I'm closing this as IAM roles are already supported.
