### ISSUE TITLE
Send Dashboard Links to slack in addition to Visualizations

### ISSUE THREAD

**Issue by bendok** [looker/lookerbot#113]
When a custom command is used with a dashboard with additional filters, it would be nice if a link was sent along with the image to open the dashboard with the desired filter, so you could dive deeper into the dashboard.

**Comment by wilg** [comment]
Since Lookerbot currently only supports dashboards with a single tile, what's the advantage of showing the dashboard link here versus the link to Explore? Or are the Explore links not coming through? (There should be one on every command result.)

**Comment by bendok** [comment]
Oh - the explore link isn't coming through for me. Here's a screenshot:
<img width="548" alt="screen shot 2017-07-20 at 12 45 12 pm" src="https://user-images.githubusercontent.com/954631/28429060-6367a234-6d49-11e7-9b32-b6ea8c7e16a4.png">

**Comment by bendok** [comment]
Scrap that - I'm a dummy

**Comment by bendok** [comment]
For some reason I thought that link was the image URL
