### ISSUE TITLE
Caching Query Filters Issue

### ISSUE THREAD

**Issue by bendok** [looker/lookerbot#116]
I see this behaviour when using Dashboard commands.

1. `/looker <dashboard name>`
2. Shows result, let's call it A, correctly appearing with no filters
3. `/looker <dashboard name> <filter>`
4. Shows results, let's call it B, correctly filtering with the filter
5. `/looker <dashboard name>`
6. Show's result B, incorrectly appearing with filters from step 4.

I've seen this behaviour across a few different dashboards I've setup.

**Comment by bendok** [comment]
@wilg any thoughts? I think essentially this comes down to how you handle commands when no filters are supplied

**Comment by wilg** [comment]
Looks like we fail to copy the query before we modify it to add the filters, so the previous value sticks around. I have a fix.

**Comment by bendok** [comment]
thanks!
