### ISSUE TITLE
add ALLOW_SLACK_GUEST_USERS variable

### ISSUE THREAD

**Issue by philip-martinelli** [looker/lookerbot#117]
guest users are unable to use lookerbot slack commands

![screenshot 2017-08-02 14 48 07](https://user-images.githubusercontent.com/26886953/28898044-780adb6c-7798-11e7-9fe8-41e9530f3be8.png)

**Comment by wilg** [comment]
This should exist, have you set `ALLOW_SLACK_GUEST_USERS=true`?

**Comment by rjnordeen** [comment]
works!  thanks

**Comment by philip-martinelli** [comment]
cool, you're totally right.
