### ISSUE TITLE
Cannot use look-less dashboards with Lookerbot

### ISSUE THREAD

**Issue by lameyer** [looker/lookerbot#125]
The new look-less dashboards don't seem to work with the lookerbot. They just return Not found:

![image](https://user-images.githubusercontent.com/8021670/32346771-a41a4924-bfcb-11e7-9936-3aec49d496a3.png)

**Comment by wilg** [comment]
This is strange as @jonathanswenson and I explicitly added support for this here: https://github.com/looker/lookerbot/blob/8e16496a9acb9f4f456592ee3345d309de2f261d/lib/repliers/dashboard_query_runner.ts#L36-L42

**Comment by wilg** [comment]
Fixed in 0.0.14
