### ISSUE TITLE
Add a 'looker is typing' indicator while waiting for bot?

### ISSUE THREAD

**Issue by michael-erasmus** [looker/lookerbot#13]
Other Slack bots I've seen does this, and it seems to work quite well.

![image](https://cloud.githubusercontent.com/assets/58212/13232271/52073778-d963-11e5-9c29-2627ad29fe00.png)

Curious if this would be a hard one to implement?
Might be great feedback to users to know that the bot is still running and working on returning a result.

_I think_ this might already be supported by botkit
https://github.com/howdyai/botkit/blob/9ca6d2e1762a76fa2480f083ffb251ae44b17d5a/lib/Slackbot_worker.js#L377

**Comment by wilg** [comment]
Our current loading solution addresses this in a different way.
