### ISSUE TITLE
Lookerbot doesn't work for Lookless dashboards

### ISSUE THREAD

**Issue by maxcorbin** [looker/lookerbot#131]
The root cause here is not going to be fixed in this repo because it is caused by something happening in the Looker product. I wanted to put something here so that maybe we could warn users that this is broken right now.

## Summary
Lookerbot cannot load commands in Lookless dashboards. The bot will report that the command was not found.

## Workaround
1. Click Explore from Here on the tile on that dashboard
2. Save the explore as a Look
3. Remove the Lookless tile from the dashboard
4. Apply any filters to the new Look-based tile

**Comment by wilg** [comment]
Dup of https://github.com/looker/lookerbot/issues/125, but maybe that bug isn't fixed?

**Comment by maxcorbin** [comment]
@wilg I'll check in with the person who reported this to me and see if they just need to update, thanks!
