### ISSUE TITLE
Yarn Start Error

### ISSUE THREAD

**Issue by hqu2018** [looker/lookerbot#133]
Hello, 
I am getting error when trying to start yarn and deploy the bot. I attached the error messages as follows. The strange issue it that I set Bot User OAuth Access Token  as Slack api key, but it shows could not connect to the SLACK API.
$ ./node_modules/.bin/ts-node ./src/index.ts
Using Looker information specified in individual environment variables.
Couldn't fetchAccessToken for Looker undefined: Error: Invalid URI "undefined/login"
No commands specified for undefined...
Starting SlackService
info: ** No persistent storage method specified! Data may be lost when process shuts down.
info: ** Setting up custom handlers for processing Slack messages
info: ** API CALL: https://slack.com/api/rtm.start
info: ** API CALL: https://slack.com/api/team.info
info: ** Starting webserver on port 3333
info: ** Serving webhook endpoints for Slash commands and outgoing webhooks at: http://MY_HOST:3333/slack/receive
Started StaticListener
Started DataActionListener
Started HealthCheckListener
Started ScheduleListener
Slack buttons are disabled or not configured.
Started SlackEventListener
Checked for updates from https://api.github.com/repos/looker/lookerbot/releases/latest. No new version available.
Checked for updates from https://api.github.com/repos/looker/lookerbot/releases/latest. No new version available.
Checked for updates from https://api.github.com/repos/looker/lookerbot/releases/latest. No new version available.
Checked for updates from https://api.github.com/repos/looker/lookerbot/releases/latest. No new version available.

/Users/Huiying/Desktop/lookerbot-master/src/services/slack_service.ts:49
        throw new Error(`Could not connect to the Slack API. Ensure your Slack API key is correct. (${err})`)
              ^
Error: Could not connect to the Slack API. Ensure your Slack API key is correct. (not_authed)
    at defaultBot.api.team.info (/Users/Huiying/Desktop/lookerbot-master/src/services/slack_service.ts:49:15)
    at Request._callback (/Users/Huiying/Desktop/lookerbot-master/node_modules/botkit/lib/Slack_web_api.js:22:33)
    at Request.self.callback (/Users/Huiying/Desktop/lookerbot-master/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/Huiying/Desktop/lookerbot-master/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/Huiying/Desktop/lookerbot-master/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Great Thanks,
Huiying

**Comment by wilg** [comment]
This line indicates to me that your environment variables are not getting properly set:

`Couldn't fetchAccessToken for Looker undefined: Error: Invalid URI "undefined/login"`
