### ISSUE TITLE
Disallow responses to users from other Slack teams via shared channels

### ISSUE THREAD

**Issue by reedloden** [looker/lookerbot#137]
[Shared channels](https://api.slack.com/shared-channels) have added a new degree of complexity to user management.

Similar to #86, I don't want users on other Slack teams to be able to interact with Lookerbot.

https://api.slack.com/types/user#user_objects_from_workspaces_connected_through_shared_channels

Perhaps check `is_stranger`? Or check that the team ID is the same?

**Comment by a-zndr** [comment]
Yes please!!!! as looker can be both invoked in DM and in channel!
