### ISSUE TITLE
Opening the concerned dashboard/look/graph/text of looker in slack by a command typed in Slack

### ISSUE THREAD

**Issue by nishantsingodia** [looker/lookerbot#140]
I am not a coder and am involved in Product Management. Through slack messaging I want to ensure that through certain commands the respective analysis of Looker is showed in the slack itself rather than searching for the link on looker and then pasting it in slack. I've created a basic lookerbot as showed in the tutorial and created a command '/looker' which has only 1 built in command - 'find'. How can I add more commands to open the concerned dashboard/look/graph/text. If you could please provide a very detailed guide it would be great, as I am not a coder and am not accustomed to coding terms and technicalities.

**Comment by wilg** [comment]
Also if you're still stuck, emailing our support team at support@looker.com may be the quickest route as they can walk you through the steps over email or chat.
