### ISSUE TITLE
dashboard query runner should use result_maker_id rather than query. and handle new listen changes

### ISSUE THREAD

**Issue by arkarkark** [looker/lookerbot#142]
to support Merge Results dashboard elements might not have a 'query'. We should use the new result_maker.id that is on the element to run the query.

To do that you just send an object with {result_maker_id: THE_ID} to multi_run_async.

If you want to add filters to the query then you just add a filters: hash (the hash has key of field_name value of filter_value).

also note that dashboard_element.listen is now deprecated since each element may have more than one filterable thing on it. you can get the listen for each filterable thing on a dashboard_element from `result_maker.filterables[].listen`

and the format changed from `{<dashboard_filter_name>: <field_name>}` to `[{dashboard_filter_name: <the_dashboard_filter_name>, field: <field_name>}, {dashboard_filter_name: <the_dashboard_filter_name>, field: <field_name>}, ...]`

we need to handle both types of `listen` and `result_maker.filterables[].listen`

**Comment by apstrong** [comment]
@ankit-bhatia-looker how is this related to data-delivery?
